### ISSUE TITLE
Incorrect implementation of `Opcode.__str__`

### ISSUE THREAD

**Issue by gsingh93** [Maratyszcza/Opcodes#13]
We're mixing two different formatting techniques in Python [here](https://github.com/Maratyszcza/Opcodes/blob/master/opcodes/x86_64.py#L903-L904):
```
def __str__(self):
    return "0x%02X".format(self.byte)
```

**Comment by Maratyszcza** [comment]
Thank you for the bug report! Fixed in ce122a7864d84a9127394d9d5d5e64f537e69474
